Mulliken and Loewdin gross orbital population 

  atom#    atom   basisfunction     Mulliken GP      Loewdin GP
      1      Si             3s            1.29            1.11
                          3p_y            0.89            0.96
                          3p_z            0.89            0.96
                          3p_x            0.89            0.96
                         total            3.95            3.97

      2      Si             3s            1.29            1.11
                          3p_y            0.92            0.97
                          3p_z            0.92            0.97
                          3p_x            0.92            0.97
                         total            4.05            4.03

