#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --qos=premium
#SBATCH --time=04:00:00
#SBATCH --account=jcesr
#SBATCH --job-name=FW_job
#SBATCH --output=FW_job-%j.out
#SBATCH --error=FW_job-%j.error

module load qchem
cd /scratch2/scratchdirs/sblau/fragment_wf/block_2018-07-04-03-30-43-540608/launcher_2018-07-06-17-03-13-189067
rlaunch -c /global/homes/s/sblau/config_edison singleshot

# CommonAdapter (SLURM) completed writing Template
