#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --qos=premium
#SBATCH --time=03:00:00
#SBATCH --partition=regular
#SBATCH --account=jcesr
#SBATCH --job-name=FW_job
#SBATCH --output=FW_job-%j.out
#SBATCH --error=FW_job-%j.error
#SBATCH --constraint=haswell

module load qchem
cd /global/cscratch1/sd/sblau/fragment_wf/block_2018-07-10-18-45-27-601029/launcher_2018-07-17-17-03-58-683413
rlaunch -c /global/homes/s/sblau/config singleshot

# CommonAdapter (SLURM) completed writing Template
