MULLIKEN and LOEWDIN POPULATION ANALYSIS 

  atom#    atom      Mulliken charge       Loewdin charge
      1       K                 0.76                 0.64
      2       K                 0.76                 0.64
      3       K                 0.76                 0.64
      4       K                 0.76                 0.65
      5      Sn                 0.81                 0.80
      6      Sn                 0.81                 0.80
      7      Sn                 0.80                 0.79
      8      Sn                 0.82                 0.81
      9       O                -1.06                -0.97
     10       O                -1.04                -0.96
     11       O                -1.07                -0.98
     12       O                -1.08                -0.99
     13       O                -1.03                -0.95
     14       O                -1.03                -0.95

          total                -0.00                -0.00
